[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "*"
  to = "/.netlify/functions/:splat"
  status = 200
